export { default as NavBar } from "./NavBar/NavBar"
export { default as MainPage} from "./MainPage/MainPage"
export { default as HomeSection} from "./MainPage/HomeSection/HomeSection"
export { default as Navigation } from "./NavBar/Navigation"
export { default as MobileNav } from "./NavBar/MobileNav"
export { default as AboutMe } from "./MainPage/About/AboutMe"
export { default as Porfolio } from "./MainPage/Portfolio/Portfolio"
export { default as Contact } from "./MainPage/Contact/Contact"
export { default as Footer } from "./MainPage/Footer/Footer"
export { default as Resume } from "./Resume/Resume"